---
name: XML-TreeBuilder
version: 3.10_2
author:
  - 'Jeff Fearn <Jeff.Fearn@gmail.com>'
abstract: XML elements with the same interface as HTML::Element
license: perl
resources:
  license: ~
requires:
  HTML::Element: 4
  HTML::Tagset: 3.02
  XML::Parser: 0
build_requires:
  Devel::Cover: 0
  HTML::Element: 4
  HTML::Tagset: 3.02
  Module::Build: 0
  Test::Exception: 0
  Test::More: 0
  Test::Perl::Critic: 0
  Test::Pod::Coverage: 0
  XML::Parser: 0
provides:
  XML::Element:
    file: lib/XML/Element.pm
    version: 3.10_2
  XML::TreeBuilder:
    file: lib/XML/TreeBuilder.pm
    version: 0
generated_by: Module::Build version 0.32
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
